version: "3"
services:
    hub:
      image: selenium/hub
      ports:
        - "4444:4444"
    chrome:
      image: selenium/node-chrome
      shm_size: "1gb"
      depends_on:
        - hub
      environment: 
        - HUB_HOST=hub  
      volumes:
      - ./downloads:/home/seluser/Downloads 
    firefox:
      image: selenium/node-firefox
      shm_size: "1gb"
      depends_on:
        - hub
      environment: 
        - HUB_HOST=hub  
      volumes:
      - ./downloads:/home/seluser/Downloads   
    search-module:
      image: avadooty/selenium-docker    
      depends_on:
        - chrome
        - firefox
      environment:
        - BROWSER=firefox
        - HUB_HOST=hub
        - MODULE=search-module.xml
      volumes:
        - ./output/search-result:/usr/share/udemy/test-output
    book-flight-module:
      image: avadooty/selenium-docker    
      depends_on:
        - chrome
        - firefox
      environment:
        - BROWSER=chrome
        - HUB_HOST=hub
        - MODULE=book-flight-module.xml
      volumes:
        - ./output/book-flight-result:/usr/share/udemy/test-output  